service:
  name: cmp-guide-step-functions

plugins:
  - serverless-webpack
  - serverless-step-functions

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-southeast-2'}
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  handleSQS:
    handler: handler.handleSQS

stepFunctions:
  stateMachines:
    mathStateMachine:
      name: mathStateMachine
      definition:
        Comment: my math state machine
        StartAt: SQSSendMessage
        States:
          SQSSendMessage:
            Type: Task
            Resource: arn:aws:states:::sqs:sendMessage
            Parameters:
              QueueUrl: 
                Ref: MyQueue
              MessageBody.$: $ # take input object, and pass it to messge context
            Next: HandleSQS
          HandleSQS:
            Type: Task
            Resource: 
              Fn::GetAtt: ['handleSQS', 'Arn']
            End: true


resources:
  Resources:
    MyQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: my-queue