service:
  name: cmp-guide-step-functions

plugins:
  - serverless-webpack
  - serverless-step-functions

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-southeast-2'}
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  sqs:
    handler: handler.sqs

stepFunctions:
  stateMachines:
    mathStateMachine:
      name: mathStateMachine
      definition:
        Comment: my math state machine
        StartAt: PutDynamoDBItem
        States:
          PutDynamoDBItem:
            Type: Task
            Resource: arn:aws:states:::dynamodb:putItem
            ResultPath: $.response
            Parameters:
              TableName: 
                Ref: MyDynamoDBTable1
              Item.$: $.item # take input object, and pass it to messge context
            Next: SetNameForQuery
          SetNameForQuery:
            Type: Pass
            Result:
              id: Jeremy
              score: "42"
            Next: GetDynamoDBItem
          GetDynamoDBItem:
            Type: Task
            Resource: arn:aws:states:::dynamodb:getItem
            Parameters:
              TableName: 
                Ref: MyDynamoDBTable1
              Key.$: $ # now Key is { "id":"Jeremy", "score":"42" } provided by SetNameForQuery
            End: true
          


resources:
  Resources:
    MyDynamoDBTable1:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: MyDynamoDBTable1
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: score
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: score
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1